workspace = { members = ["vrrp_packet"] }
[package]
name = "failover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
vrrp_packet = { path = "vrrp_packet", version = "0.1.0" }
