name: failover
version: '0.3.1'
summary: A rust implementation of VRRP
description: |
  Failover is a rust implementation of the VRRP protocol. 

  VRRP is a redundancy protocol that achieves this by 'creating' a virtual device with virtual network parameters. 

  The protocol has been tested together with `keepalived` and will soon be tested with routers and switches from major vendors.
  

grade: stable
confinement: devmode
base: core22

parts:
  failover:
    plugin: rust
    source: .

apps:
  main:
    command: bin/failover file-mode
    daemon: simple 
    post-stop-command: bin/failover file-mode --action teardown
